<?php
/**
 * Formats diagnostic results as a Markdown report suitable for sharing.
 *
 * @package Update_Doctor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Update_Doctor_Report_Formatter {

	/**
	 * @param array $results Output of Update_Doctor_Runner::run_all().
	 * @return string Markdown report.
	 */
	public function format( array $results ) {
		global $wp_version;

		$out  = "# Update Doctor diagnostic report\n\n";
		$out .= sprintf( "- Site: %s\n", home_url() );
		$out .= sprintf( "- WordPress: %s\n", $wp_version );
		$out .= sprintf( "- PHP: %s\n", PHP_VERSION );
		$out .= sprintf( "- Update Doctor: %s\n", UPDATE_DOCTOR_VERSION );
		$out .= sprintf( "- Generated: %s UTC\n", gmdate( 'Y-m-d H:i:s' ) );
		$out .= "\n";

		foreach ( $results as $section ) {
			$out .= sprintf( "## %s\n\n", $section['label'] );
			if ( ! empty( $section['description'] ) ) {
				$out .= $section['description'] . "\n\n";
			}

			if ( empty( $section['diagnostics'] ) ) {
				$out .= "_No findings._\n\n";
				continue;
			}

			foreach ( $section['diagnostics'] as $diag ) {
				$out .= sprintf( "### %s %s\n\n", $this->status_icon( $diag->status ), $diag->title );
				if ( $diag->message ) {
					$out .= $diag->message . "\n\n";
				}
				if ( ! empty( $diag->details ) ) {
					foreach ( $diag->details as $key => $value ) {
						if ( is_int( $key ) ) {
							$out .= sprintf( "- %s\n", is_scalar( $value ) ? (string) $value : wp_json_encode( $value ) );
						} else {
							$out .= sprintf( "- **%s:** %s\n", $key, is_scalar( $value ) ? (string) $value : wp_json_encode( $value ) );
						}
					}
					$out .= "\n";
				}
			}
		}

		$out .= "---\n\n";
		$out .= "_Generated by [Update Doctor](https://github.com/csmcneill/update-doctor)._\n";

		return $out;
	}

	private function status_icon( $status ) {
		switch ( $status ) {
			case Update_Doctor_Diagnostic::STATUS_PASS:
				return '[OK]';
			case Update_Doctor_Diagnostic::STATUS_WARN:
				return '[WARN]';
			case Update_Doctor_Diagnostic::STATUS_FAIL:
				return '[ISSUE]';
			default:
				return '[INFO]';
		}
	}
}
